### ISSUE TITLE
Release of the Code

### ISSUE THREAD

**Issue by MaybeRichard** [xmed-lab/GeCA#1]
Hello, I read your article recently and it's really interesting! Looking forward for your following update about the code.

**Comment by marwankefah** [comment]
Hi Richard,

Apologies for the delayed response; it’s been a busy period. I’ve released the code and model—feel free to use the `model.py` with the [Fast-DiT](https://github.com/chuanyangjin/fast-DiT) repository. I’ve also included the training and evaluation functions, and I’ll be releasing the model weights soon.

Best regards,  
Marawan Elbatel
